# Generated by Django 3.2.23 on 2024-10-15 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maytinhketnoi',
            name='chu_so_huu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.nhanvien'),
        ),
    ]
