# Generated by Django 3.2.23 on 2024-11-06 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phong', '0002_alter_maytinhketnoi_chu_so_huu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baocao',
            name='id_NguoiLap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.nhanvien'),
        ),
        migrations.AlterField(
            model_name='buocbaocao',
            name='id_NguoiLap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.nhanvien'),
        ),
        migrations.AlterField(
            model_name='dauviec',
            name='id_NguoiLap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.nhanvien'),
        ),
        migrations.AlterField(
            model_name='duan',
            name='nhan_vien_lap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phong.nhanvien'),
        ),
        migrations.AlterField(
            model_name='ghichu',
            name='nguoi_lap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.nhanvien'),
        ),
        migrations.AlterField(
            model_name='maukichban',
            name='id_NguoiLap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.nhanvien'),
        ),
        migrations.AlterField(
            model_name='nhomchiase',
            name='id_NguoiLap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.nhanvien'),
        ),
        migrations.AlterField(
            model_name='phancong',
            name='id_NguoiLap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.nhanvien'),
        ),
        migrations.AlterField(
            model_name='quytrinh',
            name='nguoi_duyet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phong.nhanvien'),
        ),
        migrations.AlterField(
            model_name='ruiro',
            name='nguoi_lap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.nhanvien'),
        ),
        migrations.AlterField(
            model_name='ruiroxuly',
            name='nguoi_lap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.nhanvien'),
        ),
    ]
