# Generated by Django 3.2.23 on 2024-07-22 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanEngine', '0002_uploadfile'),
        ('startScan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SASTScan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_scan_date', models.DateTimeField()),
                ('stop_scan_date', models.DateTimeField(blank=True, null=True)),
                ('scan_status', models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2), (3, 3)], default=-1)),
                ('results', models.JSONField(blank=True, null=True)),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanEngine.uploadfile')),
            ],
        ),
    ]
