# Generated by Django 3.2.23 on 2024-09-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon_note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguonLoHong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_nguon', models.CharField(max_length=255)),
                ('ky_hieu', models.CharField(max_length=50)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('duong_dan', models.URLField(max_length=300)),
            ],
        ),
    ]
