# Generated by Django 3.2.23 on 2024-09-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recon_note', '0002_nguonlohong'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiaiDoanPhatTrien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NenTangPhatTrien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoSoPhanMem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nguoi_them', models.CharField(max_length=100)),
                ('phien_ban', models.CharField(max_length=50)),
                ('mo_ta', models.TextField(blank=True)),
                ('tai_lieu', models.CharField(max_length=300)),
                ('giai_doan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon_note.giaidoanphattrien')),
                ('nen_tang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon_note.nentangphattrien')),
            ],
        ),
    ]
