# Generated by Django 3.2.23 on 2024-09-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon_note', '0003_giaidoanphattrien_hosophanmem_nentangphattrien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosophanmem',
            name='tai_lieu',
            field=models.FileField(blank=True, upload_to='file_upload/'),
        ),
    ]
