# Generated by Django 3.2.23 on 2024-10-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phong', '0001_initial'),
        ('recon_note', '0004_alter_hosophanmem_tai_lieu'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienPhap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_bien_phap', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiBienPhap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_loai_bien_phap', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiLoHong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhienBanThietKe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, max_length=255, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('so_phien_ban', models.CharField(blank=True, max_length=50, null=True)),
                ('trang_thai', models.CharField(blank=True, max_length=255, null=True)),
                ('du_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.duan')),
            ],
        ),
        migrations.AlterField(
            model_name='hosophanmem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TaiLieuThietKe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, max_length=255, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('duong_dan', models.CharField(blank=True, max_length=255, null=True)),
                ('trang_thai', models.CharField(blank=True, max_length=255, null=True)),
                ('phien_ban_thiet_ke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon_note.phienbanthietke')),
            ],
        ),
        migrations.CreateModel(
            name='PhienBanGiaiDoan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('giai_doan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon_note.giaidoanphattrien')),
                ('phien_ban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.phienbanduan')),
            ],
        ),
        migrations.CreateModel(
            name='LoHong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_lo_hong', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('muc_do', models.CharField(max_length=255)),
                ('id_BienPhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon_note.bienphap')),
                ('id_LoaiLoHong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon_note.loailohong')),
                ('id_NguonLoHong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon_note.nguonlohong')),
            ],
        ),
        migrations.CreateModel(
            name='HoSoThietKe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, max_length=255, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('nguoi_tai_len', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.nguoidung')),
                ('phien_ban_thiet_ke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon_note.phienbanthietke')),
            ],
        ),
        migrations.CreateModel(
            name='DuAnNenTang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
                ('thuoc_bo_tieu_chuan', models.CharField(max_length=1000, null=True)),
                ('du_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.duan')),
                ('nen_tang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon_note.nentangphattrien')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietBienPhap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_loai_bien_phap', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('tai_lieu', models.CharField(blank=True, max_length=2000)),
                ('id_BienPhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon_note.bienphap')),
                ('id_LoaiBienPhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon_note.loaibienphap')),
                ('id_NguoiLap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phong.nguoidung')),
            ],
        ),
    ]
